## Berekenen van de droogte-indicator {#h3-3:indicator}

Kennen we de kritische drempelwaarde dan kan de droogte-indicator vrij eenvoudig berekend worden.
Eerst tellen we voor elke meetlocatie, elk jaar en elke simulatie het aantal dagen dat het grondwaterpeil onder de kritische drempelwaarde is $=dagen\_droog_{meetlocatie_m; simulatie_s; jaar_j}$. 
Voor de periode 1985 - 2018, 58 meetlokaties en 20 simulaties betekent dit dus 34 * 58 * 20 = 39440 ${\text {dagen\_droog}}$-waarden

```{block2 definitie-droogte-indicator, type="exampleblock", latex.options="{}", echo = TRUE}
De droogte-indicator voor een bepaald jaar $j$ is dan het gemiddelde van deze aantallen droge dagen voor alle simulaties en meetlocaties: ${\text {droogte-ind}}_{j} = \frac{\sum_{s=1}^{20}\sum_{m=1}^{58}{\text {dagen\_droog}}_{m;s;j}}{20*58}$

```

Momenteel wordt de droogte-indicator berekend op basis van 58 meetlocaties. 
Er zijn er echter een honderdtal voorzien.
Mettertijd zal de droogte-indicator op een groter aantal punten berekend worden. 
Het mogelijke effect op de indicatorwaarden zal ingeschat worden door ook de waarde voor de huidige 58 locaties te blijven berekenen.

Het wordt complexer als we inzicht willen krijgen in de onzekerheid die er op de droogte-indicator zit, m.a.w. wat is het betrouwbaarheidsinterval van de droogte-indicator ? 

Hiervoor doen we een beroep op de formule van Rubin [@RN6220].
We geven eerst de inhoudelijke betekenis, Vooraleer we de mathematische uitwerking geven.
De totale variantie in de data kan beschouwd worden als een optelling van twee varianties, een variantie die inherent is aan de data en een bijkomende variantie die voorvloeit uit de onzekerheid over de schatting van ontbrekende waarden (= variantie door imputatie).
In het geval van de droogteindicator wordt (voor één bepaald jaar) de variantie die inherent is aan de data geschat op basis van de verschillen in de indicatorwaarden tussen de meetpunten.
De variantie door imputatie wordt geschat op basis van de verschillende simulaties. 
Deze is vooral bepaald door voor de simulaties de afwijkingen tussen de indicatorwaarden te berekenen.

Kennen we de variantie kan hiermee, op basis van de centrale limietstelling, voor elk jaar een betrouwbaarheidsinterval berekend worden.

Mathematisch wordt het betrouwbaarheidsinterval door de hieronder gegeven formules berekend. 

$${\mbox{de droogte-indicator voor één simulatie en één jaar : droogte-ind-sim}}_{j;s} =  \sum_{m = 1}^{58}({\mbox {dagen\_droog}}_{m;s;j}) / 58 $$
$${\text {de droogte-indicator voor één jaar : droogte-ind}}_{j} =  \sum_{s = 1}^{20}(\frac{\sum_{m=1}^{58}{\text {dagen\_droog}}_{m;s;j}}{58}) / 20 $$

$$ \bar\sigma^2_{{\text {droogte-ind}}_{j}} = \frac{\sum_{s = 1}^{20}\widehat{\sigma}^2_{{\text {droogte-ind-sim}}_{j;s}}}{20} + (1 + 1/20)\frac{\sum_{s=1}^{20}({\text {droogte-ind-sim}}_{j;s} - {\text {droogte-ind}}_{j})^2}{(20 - 1)}$$

De ondergrens van het betrouwbaarheidsinterval (LCL) voor een bepaald jaar $j$ wordt dan :

$$ {\text {LCL}}_j = {\text{droogte-ind}}_{j} - 1.96  \bar\sigma_{{\text {droogte-ind}}_{j}}$$

De bovengrens van het betrouwbaarheidsinterval (UCL) voor een bepaald jaar $j$ wordt dan :

$$ {\text {UCL}}_j = {\text{droogte-ind}}_{j} + 1.96  \bar\sigma_{{\text{droogte-ind}}_{j}}$$


## Berekenen van de evolutie/trend van de droogte-indicator {#h3-4:trend}

Om de trend in de droogte-indicator over de jaren heen te detecteren, worden twee soorten tijdreeksanalyse uitgevoerd. 

Ten eerste berekenen we een rollend (meerjarig) gemiddelde van de droogte-indicator.
Men heeft verschillende mogelijkheden om dergelijk gemiddelde te berekenen, ongewogen of bijv. gewogen op basis van een lineaire trend, exponentiële functie etc.
Bij een gewogen gemiddelde wenst men dat de jaren die het dichtst bij het jaar in kwestie liggen relatief meer kunnen bijdragen.
We kiezen hier voor een eenvoudig, ongewogen, gemidddelde om dat dit beter het effect van een rollend gemiddelde op de evolutie weerspiegelt.
Een andere keuze die men moet maken is of men alleen een gemiddelde berekent voor de jaren voordien of dat men dit wenst te centreren in een venster dat zowel oudere als recentere jaren omvat.
We kiezen voor het eerste, waarbij alleen oudere jaren in het tijdsvenster zitten.

We berekenen een rollend gemiddelde voor een aantal tijdvensters (2, 4, 6, 8, 10 en 30 jaar). 
Net zoals bij de originele waarden kan voor een rollend gemiddelde met behulp van de formule van Rubin ook een betrouwbaarheidsinterval bepaald worden. 

Daarnaast worden op de tijdreeksen van de droogte-indicator, zowel de originele waarden als de rollende gemiddelden, een tijdreeksmodel toegepast. 
Hierbij wordt getracht de evolutie te schatten. 
Het voordeel van een model is dat men zo bijvoorbeeld de invloed van de verschillende meetpunten op de variatie van de indicator kan inschatten.

Voor elke simulatie verloopt die berekening als volgt: een Bayesiaans mixed model, met een zero-inflated negatieve binomiale verdeling en jaar als factor schat de kans in dat een gesimuleerde dagwaarde zich onder de drempel bevindt. 
Het effect van de factor “jaar” wordt beschreven door een random walk-functie van de tweede orde. 
Meer informatie over dergelijke modellen is o.a. te vinden in @RN6221

Per jaar (en simulatie) wordt een gemiddelde waarde met haar standaardafwijking berekend. 
In tegenstelling met ${\text {droogte-ind}}_{j}$ worden aan die berekening voorwaarden gekoppeld, namelijk dat het effect van een jaar afhangt van de vorig(e) jaar/jaren volgens een tweede orde functie en ook dat een meetpunt een vaste (maar onbekende) bijdrage levert (dus dat meetpunten systematisch droger of natter kunnen zijn).
$${\text{dagen\_droog}}_{j;m;s} \sim NB(\overline{{\text{droogte-ind-sim}}}_{j;m;s}, \theta)  $$

$$\overline{{\text{droogte-ind-sim}}}_{j;m;s} = E({\text{dagen\_droog}}_{j;m;s}) \sim {\text {jaar}_j} + (1 \vert{\text{meetlocatie}_m})  $$
of 

$$\log(\overline{{\text{droogte-ind-sim}}}_{j;m;s}) = \beta_0 + \beta_1T_j + t_j + b_m + \epsilon_{jms}$$
$\beta_0$ is de intercept

$\beta_1T_j$ is het specifiek effect/bijdrage van een jaar

$t_j$ is een term ('random walk') die toelaat om rekening te houden met het feit dat het effect van het ene jaar mogelijk afhankelijk is van dat van één of meer van de voorgaande jaren.

Hier beschrijven we die mogelijke afhankelijkheid als een twee-orde relatie:
$$ \Delta^2 t_i = \Delta t_{i+1} - \Delta t_i = t_{i+1} - 2t_i + t_{i-1}$$
$$ \Delta^2 t_i \sim  N(0,\sigma^2)$$

De term  $\beta_1T_j + t_j =  \text{Trend}_j$ beschrijft de trend .
Het is dus deze term die ons hier interesseert.

$b_m$ is het mogelijke systematische effect van een meetpunt. 
We nemen aan dat deze effecten normaal verdeeld zijn: $b_m \sim N(0, \sigma _m)$.

Doordat voor elk meetpunt er op basis van de referentieperiode een specifieke kritische drempelwaarde werd bepaald zodanig dat voor elk meetpunt de overschrijding van het aantal droge dagen gemiddeld gelijk is (namelijk 18 dagen), zal de bijdrage van dit effect aanvankelijk relatief gering zijn.
Alleen meetpunten waarbij de grondwaterpeilen geen trend vertonen (cf. verdroging of vernatting) werden geselecteerd.
Daarom kunnen we ook aannemen dat, minstens voor de referentieperiode, de locatie-effecten stabiel in de tijd zullen zijn.

$\epsilon_{jms}$ is de term voor de random ruis in de log-schaal.
$$\epsilon_{jms} \sim N(0,\sigma_{jms}^2) $$
Voor het bepalen van de onzekerheid, de betrouwbaarheidsintervallen, van de trendwaarden doen we opnieuw een beroep op de formule van Rubin [@RN6220].
Om de onzekerheid in de trend te kunnen inschatten afkomstig van het schatten van peilen, wordt er niet één model berekend, maar wordt een model voor elke simulatie berekend.

$${\text{de trend van de droogte-indicator berekend voor één jaar : }} \overline{{\text {droogte-ind}}}_{j} =  \sum_{s = 1}^{20}(\overline{{\text {droogte-ind-sim}}}_{j;m;s} / 20 $$



$$ \bar\sigma^2_{\overline{{\text {droogte-ind}}}_{j}} = \frac{\sum_{s = 1}^{20}\widehat{\sigma}^2_{\overline{{\text {droogte-ind-sim}}}_{j;s}}}{20} + (1 + 1/20)\frac{\sum_{s=1}^{20}(\overline{{\text {droogte-ind-sim}}}_{j;s} - \overline{{\text {droogte-ind}}}_{j})^2}{(20 - 1)}$$

De ondergrens van het betrouwbaarheidsinterval (LCL) voor een bepaald jaar $j$ wordt dan :

$$ {\text {LCL}}_j = \overline{{\text {droogte-ind}}}_{j} - 1.96 \bar\sigma_{\overline{{\text {droogte-ind}}}_{j}}$$

De bovengrens van het betrouwbaarheidsinterval (UCL) voor een bepaald jaar $j$ wordt dan :

$$ {\text {UCL}}_j = \overline{{\text {droogte-ind}}}_{j} + 1.96 \bar\sigma_{\overline{{\text {droogte-ind}}}_{j}}$$


Het berekenen van de droogte-indicator en de betrouwbaarheid en trend ervan werden uitgevoerd met R versie 4.0.2 [@RN6222] en met het softwarepakket INLA [@RN6223].

