# Inleiding {#h1:inleiding}
Driekwart van de voor Vlaanderen en Europa meest waardevolle natuurtypes, steunen voor hun voortbestaan op grondwater. Grondwaterafhankelijke vegetaties komen voor in en op de rand van kwelgebieden, beekvalleien, vijvers en poelen. 
De vochtige gebieden vertonen vaak veel gradiënten en herbergen daarom een hoge biodiversiteit (De Becker, 2020). 
Als het grondwater door verdroging van samenstelling verandert, of systematisch buiten het bereik van de plantenwortels en de bovengrondse delen van waterplanten valt, krijgen typische soorten het moeilijk. 
Slagen die soorten er niet in om zich aan te passen of om hun leefgebied te verschuiven, dan dreigen ze te verdwijnen. 
Dat risico wordt groter als bijvoorbeeld het landgebruik of het grondwaterregime in de omgeving de beschikbare ruimte om uit te wijken beperkt. 

# Monitoring droogte in Vlaanderen {#h2:monitoring}
Monitoring is het op regelmatige tijdstippen gestandaardiseerd beschrijven van een maatstaf. 
Deze maatstaf moet toelaten om een bepaalde doelstelling of toestand te beoordelen.
Toegepast op dit onderzoek, wil dit zeggen dat we een droogte-indicator zoeken, waarmee de droogte op een gestandaardiseerde wijze in droogtegevoelige locaties/vegetaties in Vlaanderen op jaarbasis kan opgevolgd worden.

Een gestandaardiseerde wijze wordt in dit onderzoek beschouwd als een vast aantal meetpunten waar het grondwaterpeil op reguliere basis op een uniforme manier wordt gemeten.
Het vast aantal meetpunten krijgt vorm door middel van een meetnet (zie \@ref(h2-1:meetnet)).
Om droogte adequaat en zo precies mogelijk te kunnen opvolgen, menen we dat dagelijkse metingen aangewezen zullen zijn.
Als maatstaf gaan we op zoek naar een gepaste droogte-indicator (zie \@ref(h2-2:indicator)).

## Droogtemeetnet {#h2-1:meetnet}
Om in Vlaanderen een globaal beeld te krijgen van de evolutie van de grondwaterstanden op middellange tot lange termijn in verdrogingsgevoelige vegetaties werd een meetnet van een honderdtal punten ontworpen. 
Op schaal Vlaanderen is dit een relatief laag aantal. 
Wil men op deze schaal veralgemeenbare uitspraken kunnen maken, moet de keuze van deze punten zo goed mogelijk ruimtelijk gebalanceerd gebeuren. 
Ook moet er rekening gehouden worden met mogelijke verschillen in het gedrag van het grond/oppervlaktewaterpeil t.a.v. een neerslagtekort. 
@RN6212 geven een toelichting hoe dit meetnet concreet werd ontworpen. 

## Droogte-indicatoren {#h2-2:indicator}
Een volgende vraag die zich stelt, is een goede maat te vinden voor het bepalen van droogte in verdrogingsgevoelige vegetaties.
Deze maat is onder andere afhankelijk van de gewenste doelstelling. 
Zo kunnen bijv. de maten verschillen voor het vaststellen van de eerste tekenen van droogte en voor een algemeen beeld van droogte op jaarbasis. 
In dit rapport wordt een indicator gezocht voor deze laatste doelstelling. 
Ze moet dus toelaten om op jaarbasis de algemene droogte-toestand van verdrogingsgevoelige vegetaties weer te geven. 
Drie soorten indicatoren werden hiervoor in beschouwing genomen:

- een *cumulatieve*: **de som per jaar van de diepte van het grondwaterpeil beneden een kritische drempelwaarde** 

- een *absolute*: **aantal dagen per jaar dat het grondwaterpeil beneden een kritische drempelwaarde is**

- een *relatieve*: **aantal relatief droge dagen per jaar** 
Een relatief droge dag is een dag waarbij het grondwaterpeil lager staat dan een bepaalde percentielwaarde voor die dag in een bepaalde periode.
We gaan verder in dit hoofdstuk wat dieper in op de beweegredenen om  voor de beleidsrapportering een absolute indicator te verkiezen. 

### Bepalen referentietoestand {#h2-2-1:referentietoestand}
Een indicator vergelijkt een bepaalde toestand met een referentietoestand. 
Bij het bepalen van de referentietoestand spelen twee factoren een rol:

- welk grondwaterpeil beschouwen we als indicatief voor droogte oftewel wat is een **kritische waarde**?

- welk **tijdsvenster** hanteren we hierbij als referentie?

Als kritische drempelwaarde nemen we het grondwaterpeil dat 'normaal' op minder dan 5% van de dagen van een jaar (dit is afgerond 18 dagen) onderschreden wordt. 
Een droge dag is een dag dat het grondwaterpeil onder deze kritische drempelwaarde is. Een droog jaar is een jaar met meer dan 18 droge dagen.

Deze drempelwaarde stemt nauw overeen met de hydrologische variabele 'gemiddeld laagste grondwaterstand' (GLG) [@RN5703]. 
Dit is het gemiddelde van de drie laagste grondwaterpeilen op een jaar, met een minimum verschil van 14 dagen tussen de metingen, en dit uitgemiddeld over een zekere tijdsperiode: standaard een achttal jaar [@RN5875].
Voor vele verdrogingsgevoelige vegetaties is de GLG een belangrijke standplaatsfactor, zie bijv. [@RN4269; @RN4829; @RN5975].
De reden waarom dan niet de GLG als kritische drempelwaarde werd gekozen, ligt hem in het feit dat er een minimumaantal dagen tussen de waarnemingen moet zitten.
Dit bemoeilijkt het werken met tijdreeksen van dagelijkse metingen. 

Het tijdsvenster is een andere belangrijke factor bij het vastleggen van een referentie.
Men heeft dan te bepalen of gewerkt wordt met een vast tijdskader (van jaar a tot jaar b) of een relatief tijdkader (bijv. de laatste x jaren).
Ook de lengte van de tijdsperiode is een keuze die men moet maken.
We kiezen hier voor een vast tijdvenster van 30 jaar, nl. 1985 tot en met 2014.
Een periode van dertig jaar is gebruikelijk in klimaatstudies. 
De reden dat we voor een vast venster kiezen, is dat de trend gemakkelijker te interpreteren is. 
Ook het KMI werkt met vaste vasters, die ze periodiek herziet.
Het venster kan na bijv. vijftien jaar worden herzien: dus bijv. vanaf 2035 kan 2000 - 2029 als nieuw referentie genomen worden).
De periodieke herijking laat toe om de meer recente evolutie beter in beeld te brengen.

### Keuze indicator {#h2-2-2:indicator}

De drie soorten kandidaat-indicatoren werden onderling afgewogen op basis van twee karakteristieken:

- de ecologische duiding
- kan er een referentieniveau voor bepaald worden ?

De grondwaterstand kan een directe of indirecte invloed hebben op een aantal balansen die belangrijk zijn voor de fysiologie van een plant:

- waterbalans
- mineralenbalans
    - aanvoer van (essentiële) mineralen / zouten
    - invloed op biogeochemische processen die de beschikbaarheid van mineralen bepalen
- nutriëntenbalans
    - aanvoer van nutriënten
    - invloed op biogeochemische processen die de beschikbaarheid van nutriënten bepalen
- zuurstofbalans
    - (on)beschikbaarheid van zuurstof
    - invloed op biogeochemische processen die de beschikbaarheid van toxische stoffen bepalen
    
Een cumulatieve en een absolute droogte-indicatoren toetsen een grondwaterpeil af met een vast referentiepeil.
Ze hebben een ecologische betekenis, omdat ze uitdrukking geven aan mogelijke wijzigingen in één of meer van bovenvermelde balansen die met een peilswijziging gepaard gaan.

Een relatieve indicator [^gwindic] is niet gekoppeld aan een vast referentiepeil. 
Het referentiepeil hangt samen met de dag van het jaar.
In die zin is de ecologische betekenis ervan minder éénduidig. 
Om die reden valt een relatieve indicator af als een kandidaat indicator.

Blijft dan nog de keuze tussen een cumulatieve en een absolute droogte-indicator.
De cumulatieve geeft nog iets beter de sterkte van een eventueel voorkomende droogte aan, doordat het niet alleen rekening houdt met het aantal dagen dat het grondwaterpeil onder een referentiepeil bevindt, maar ook met de graad dat dit het geval is.
Een cumulatieve indicator heeft echter als nadeel dat het moeilijk is om een indicatorwaarde te definiëren die droge jaren van niet-droge jaren kan onderscheiden. 
Een absolute indicator laat dat wel toe.
Zo ligt, zoals hoger al werd aangehaald, het referentieniveau of baseline bij een absolute indicator o.b.v. 5% drempelwaarde op 18 dagen. Een jaar met meer dan 18 droge dagen kan als een relatief droog jaar worden beschouwd.

Conclusie:
Voor de gewenste doeleinde is een absolute droogte-indicator gebaseerd op de 5% drempelwaarde het meest aangewezen.


[^gwindic]: één van de [grondwaterstandsindicatoren](https://www.vmm.be/data/grondwaterstandindicator) van de VMM is een voorbeeld van een relatieve indicator. 



