# Werkwijze berekening droogte-indicator {#h3:methode}

Het toekomstig droogte-meetnet zal uit een honderdtal meetpunten bestaan. 
Op 58 van de geselecteerde locaties wordt het grondwaterpeil reeds verschillende jaren gemeten.

De berekening bevat vier delen:

- vervolledigen tijdreeksen
- berekenen van de kritische drempelwaarde voor elk van de meetlocaties
- berekenen van de droogte-indicator
- berekenen van de evolutie/trend van de droogte-indicator

## Vervolledigen tijdreeksen {#h3-1:tijdreeks}

Zoals in \@ref(h2-2-1:referentietoestand) werd aangehaald, willen we werken met een vast referentietijdsvenster: 1985 -  2014.
Voor geen enkele van de geselecteerde meetpunten beschikken we echter voor deze tijdsperiode over volledige tijdreeksen, t.t.z. 30 jaar * 365 metingen/jaar.

Een selectiecriterium om als meetpunt in het meetnet te kunnen worden opgenomen, was dat het verloop van de grondwaterstanden in belangrijke mate (minstens 2/3 van de variatie) kan verklaard worden door de meteorologische variabelen: neerslag en potentiële evapotranspiratie [@RN6212].
Deze eigenschap kunnen we gebruiken om ontbrekende data in de tijdreeks aan te vullen.
Hiervoor doen we een beroep op het softwareprogramma Menyanthes [@RN5899].
Het programma kan op basis van verklarende reeksen zoals neerslag en potentiële evapotranspiratie een model bouwen waarmee grondwaterpeilen kunnen worden geschat.

Voor elk van de 58 meetlocaties werd op deze basis een model gebouwd.
Met dit model werden vervolgens 20 simulaties berekend voor de periode 1985 - 2018, dus niet alleen voor de referentieperiode. 
Een effectieve veldmeting kreeg hierbij voorrang op een modelwaarde.
Dit betekent dat op dagen met werkelijke metingen de 20 reeksen steeds dezelfde waarde, nl. die van de veldmeting, zullen hebben.
Deze verschillende simulaties zullen toelaten om de onzekerheid te schatten die er bestaat voor de dagen zonder veldmeting. 

## Berekenen van de krtitische drempelwaarden {#h3-2:drempelwaarde}

Zoals in \@ref(h2-2-1:referentietoestand) besproken werd, stellen we als kritische drempelwaarde het grondwaterpeil dat 'normaal' op minder dan 5% van de dagen van een jaar (dit is afgerond 18 dagen) onderschreden wordt. 
Het ontbreekt hier nog aan duiding over wat als 'normaal' of als referentie wordt beschouwd. 
Hiervoor kijken we naar het referentietijdsvenster (1985 - 2014) en berekenen we voor elk meetlocatie de kritische drempelwaarde als het gemiddelde van de 5%-percentiel van de grondwatermetingen van een jaar binnen de periode 1985 - 2014. 
Het is dus niet de absolute percentielwaarde op alle metingen van 30 jaar. 
Stel bijvoorbeeld dat er één heel droog jaar is, waarbij de 5% droogste peilen in dat jaar vallen, dan zou kritische drempelwaarde louter op dat ene uitzonderlijke jaar gebaseerd zijn.
Dit beschouwen we als niet representatief, ook omdat de responstijd van vegetaties op wijzigende grondwaterregimes langzamer is dan één jaar. Daarom wordt hier verkozen om te werken met een gemiddelde van percentielwaarden per jaar. 
Deze werkwijze is ook analoog aan het berekenen van karakteristieke grondwaterstanden (GXG’s) voor vegetaties [@RN5875].


## Berekenen van de droogte-indicator {#h3-3:indicator}

Kennen we de kritische drempelwaarde dan kan de droogte-indicator vrij eenvoudig berekend worden.
Eerst tellen we voor elke meetlocatie, elk jaar en elke simulatie het aantal dagen dat het grondwaterpeil onder de kritische drempelwaarde is $=dagen\_droog_{meetlocatie_m; simulatie_s; jaar_j}$. 
Voor de periode 1985 - 2018, 58 meetlokaties en 20 simulaties betekent dit dus 34 * 58 * 20 = 39440 ${\textstyle {dagen_droog}}$-waarden

```{block2 definitie-droogte-indicator, type="exampleblock", latex.options="{}", echo = TRUE}
De droogte-indicator voor een bepaald jaar $j$ is dan het gemiddelde van deze aantallen droge dagen voor alle simulaties en meetlocaties: ${\text {droogte-ind}}_{j} = \frac{\sum_{s=1}^{20}\sum_{m=1}^{58}{\textstyle {dagen_droog}}_{m;s;j}}{20*58}$

```

Momenteel wordt de droogte-indicator berekend op basis van 58 meetlocaties. 
Er zijn er echter een honderdtal voorzien.
Mettertijd zal de droogte-indicator op een groter aantal punten berekend worden. 
Het mogelijke effect op de indicatorwaarden zal ingeschat worden door ook de waarde voor de huidige 58 locaties te blijven berekenen.

Het wordt complexer als we inzicht willen krijgen in de onzekerheid die er op de droogte-indicator zit, m.a.w. wat is het betrouwbaarheidsinterval van de droogte-indicator ? 

Hiervoor doen we een beroep op de formule van Rubin [@RN6220].
We geven eerst de inhoudelijke betekenis, Vooraleer we de mathematische uitwerking geven.
De totale variantie in de data kan beschouwd worden als een optelling van twee varianties, een variantie die inherent is aan de data en een bijkomende variantie die voorvloeit uit de onzekerheid over de schatting van ontbrekende waarden (= variantie door imputatie).
In het geval van de droogteindicator wordt (voor één bepaald jaar) de variantie die inherent is aan de data geschat op basis van de verschillen in de indicatorwaarden tussen de meetpunten.
De variantie door imputatie wordt geschat op basis van de verschillende simulaties. 
Deze is vooral bepaald door voor de simulaties de afwijkingen tussen de indicatorwaarden te berekenen.

Kennen we de variantie kan hiermee, op basis van de centrale limietstelling, voor elk jaar een betrouwbaarheidsinterval berekend worden.

Mathematisch wordt het betrouwbaarheidsinterval door de hieronder gegeven formules berekend. 

$${\textstyle {de droogte-indicator voor één simulatie en één jaar : droogte-ind-sim}}_{j;s} =  \sum_{m = 1}^{58}({\textstyle {dagen_droog}}_{m;s;j}) / 58 $$
$${\textstyle {de droogte-indicator voor één jaar : droogte-ind}}_{j} =  \sum_{s = 1}^{20}(\frac{\sum_{m=1}^{58}{\textstyle {dagen_droog}}_{m;s;j}}{58}) / 20 $$

$$ \bar\sigma^2_{{\textstyle {droogte-ind}}_{j}} = \frac{\sum_{s = 1}^{20}\widehat{\sigma}^2_{{\textstyle {droogte-ind-sim}}_{j;s}}}{20} + (1 + 1/20)*\frac{\sum_{s=1}^{20}({\textstyle {droogte-ind-sim}}_{j;s} - {\textstyle {droogte-ind}}_{j})^2}{(20 - 1)}$$

De ondergrens van het betrouwbaarheidsinterval (LCL) voor een bepaald jaar $j$ wordt dan :

$$ {\textstyle {LCL}}_j = {\textstyle{droogte-ind}}_{j} - 1.96 * \sqrt{\bar\sigma^2_{{\textstyle {droogte-ind}}_{j}}}$$

De bovengrens van het betrouwbaarheidsinterval (UCL) voor een bepaald jaar $j$ wordt dan :

$$ {\textstyle {UCL}}_j = {\textstyle{droogte-ind}}_{j} + 1.96 * \sqrt{\bar\sigma^2_{{\textstyle {droogte-ind}}_{j}}}$$


## Berekenen van de evolutie/trend van de droogte-indicator {#h3-4:trend}

Om de trend in de droogte-indicator over de jaren heen te detecteren, wordt een tijdreeksanalyse uitgevoerd. 


Voor elke simulatie verloopt die berekening als volgt: een Bayesiaans mixed model, met een zero-inflated negatieve binomiale verdeling en jaar als factor schat de kans in dat een gesimuleerde dagwaarde zich onder de drempel bevindt. 
Het effect van de factor “jaar” wordt beschreven door een random walk-functie van de tweede orde. 
Meer informatie over dergelijke modellen is o.a. te vinden in @RN6221

Per jaar (en simulatie) wordt een gemiddelde waarde met haar standaardafwijking berekend. 
In tegenstelling met ${\textstyle {droogte-ind}}_{j}$ worden aan die berekening voorwaarden gekoppeld, namelijk dat het effect van een jaar afhangt van de vorig(e) jaar/jaren volgens een tweede orde functie en ook dat een meetpunt een vaste (maar onbekende) bijdrage levert (dus dat meetpunten systematisch droger of natter kunnen zijn).
$${\textstyle {dagen_droog}}_{m;s;j} \sim NB(\overline{{\textstyle {droogte-ind-sim}}}_{j;s}, \theta)  $$

$$\overline{{\textstyle {droogte-ind-sim}}}_{j;s} = E({\textstyle {dagen_droog}}_{m;s;j}) \sim {\textstyle {jaar}} + (1 \vert{\textstyle{meetlocatie}})  $$
of 

$$\log(\overline{{\textstyle {droogte-ind-sim}}}_{j;s}) = \beta_0 + \beta_1T_j + t_j + b_m + \epsilon_{jm}$$
$\beta_0$ is de intercept

$\beta_1T_j$ is het specifiek effect/bijdrage van een jaar

$t_j$ is een term ('random walk') die toelaat om rekening te houden met het feit dat het effect van het ene jaar mogelijk afhankelijk is van dat van één of meer van de voorgaande jaren.

Hier beschrijven we die mogelijke afhankelijkheid als een twee-orde relatie:
$$ \Delta^2 t_i = \Delta t_{i+1} - \Delta t_i = t_{i+1} - 2t_i + t_{i-1}$$
$$ \Delta^2 t_i \sim  N(0,\sigma^2)$$

$b_m$ is het mogelijke systematische effect van een meetpunt. 
We nemen aan dat deze effecten normaal verdeeld zijn: $b_m \sim N(0, \sigma _m)$.
Doordat voor elk meetpunt er op basis van de referentieperiode een specifieke kritische drempelwaarde werd bepaald zodanig dat voor elk meetpunt de overschrijding van het aantal droge dagen gemiddeld gelijk is (namelijk 18 dagen), zal de bijdrage van dit effect aanvankelijk relatief gering zijn.
Alleen meetpunten waarbij de grondwaterpeilen geen trend vertonen (cf. verdroging of vernatting) werden geselecteerd.
Daarom kunnen we ook aannemen dat, minstens voor de referentieperiode, de locatie-effecten stabiel in de tijd zullen zijn.

$\epsilon_{jm}$ is de term voor de random ruis in de log-schaal.
$$\epsilon_{jm} \sim N(0,\sigma_{jm}^2) $$
Voor het bepalen van de onzekerheid, de betrouwbaarheidsintervallen, van de trendwaarden doen we opnieuw een beroep op de formule van Rubin [@RN6220].

$${\textstyle {de trend van de droogte-indicator berekend voor één jaar : }} \overline{{\textstyle {droogte-ind}}}_{j} =  \sum_{s = 1}^{20}(\overline{{\textstyle {droogte-ind-sim}}}_{j;s} / 20 $$



$$ \bar\sigma^2_{\overline{{\textstyle {droogte-ind}}}_{j}} = \frac{\sum_{s = 1}^{20}\widehat{\sigma}^2_{\overline{{\textstyle {droogte-ind-sim}}}_{j;s}}}{20} + (1 + 1/20)*\frac{\sum_{s=1}^{20}(\overline{{\textstyle {droogte-ind-sim}}}_{j;s} - \overline{{\textstyle {droogte-ind}}}_{j})^2}{(20 - 1)}$$

De ondergrens van het betrouwbaarheidsinterval (LCL) voor een bepaald jaar $j$ wordt dan :

$$ {\textstyle {LCL}}_j = \overline{{\textstyle {droogte-ind}}}_{j} - 1.96 * \sqrt{\bar\sigma^2_{\overline{{\textstyle {droogte-ind}}}_{j}}}$$

De bovengrens van het betrouwbaarheidsinterval (UCL) voor een bepaald jaar $j$ wordt dan :

$$ {\textstyle {UCL}}_j = \overline{{\textstyle {droogte-ind}}}_{j} + 1.96 * \sqrt{\bar\sigma^2_{\overline{{\textstyle {droogte-ind}}}_{j}}}$$


Het berekenen van de droogte-indicator en de betrouwbaarheid en trend ervan werden uitgevoerd met R versie 4.0.2 [@RN6222] en met het softwarepakket INLA [@RN6223].

